apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-backend-config
  namespace: three-tier

data:
  SPRING_DATASOURCE_URL: jdbc:mysql://todo-mysql-svc:3306/todo_app?useSSL=false&allowPublicKeyRetrieval=true