apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: todo-mysql
  namespace: three-tier

spec:
  serviceName: todo-mysql-svc

  replicas: 1

  selector:
    matchLabels:
      app: todo-mysql

  template:
    metadata:
      labels:
        app: todo-mysql

    spec:
      containers:
        - name: mysql

          image: mysql:8.0.42

          ports:
            - containerPort: 3306

          env:

            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: todo-mysql-secret
                  key: SPRING_DATASOURCE_PASSWORD

            - name: MYSQL_DATABASE
              value: todo_app

          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"

      volumes:
        - name: mysql-volume
          persistentVolumeClaim:
            claimName: mysql-volume-claim