apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: three-tier

spec:
  selector:
    role: frontend

  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

  type: ClusterIP